### ISSUE TITLE
404 error

### ISSUE THREAD

**Issue by lm699** [tttooommm56/MMM-RainForecast-FR#2]
Bonjour,
Merci pour ton development, je rencontre un problème : les données ne s'affichent pas pour mon cas. Je mets bien l'id insee mais j'ai "pas de données disponibles".
Je ne sais pas si c'est lié, l'url dans le module retourne une erreur 404 lorsque je la lance depuis un navigateur : http://www.meteofrance.com/mf3-rpc-portlet/rest/pluie/
Merci de m'indiquer la marche à suivre, si possible :)
Thx

**Comment by tttooommm56** [comment]
Les prévisions pluie ne sont pas disponibles pour toutes les villes.
As-tu vérifié sur le site de Météo France qu'il y avait bien des prévisions pour ta ville ?
-> http://www.meteofrance.com/previsions-meteo-france/previsions-pluie

**Comment by lm699** [comment]
Merci pour ta réponse,
Oui bien-sûr, j'habite au Creusot (71) et j'ai bien les données météo : http://www.meteofrance.com/previsions-meteo-france/previsions-pluie/le-creusot/71200

**Comment by tttooommm56** [comment]
Je viens de tester chez moi, ça fonctionne bien avec le code INSEE du Creusot : 71153
En ce moment il n'y a pas de pluie prévue ;-)
L'url appelée par le module est la suivante : http://www.meteofrance.com/mf3-rpc-portlet/rest/pluie/711530

**Comment by lm699** [comment]
Bon, je vais ré essayer, je te tiens au courant dans la semaine. Merci pour ta réponse

**Comment by tttooommm56** [comment]
@lm699 as-tu réussi à faire fonctionner le module ?
