### ISSUE TITLE
bonjour

### ISSUE THREAD

**Issue by seramik** [tttooommm56/MMM-RainForecast-FR#3]
bonjour
je teste ton module qui m'interresse beaucoup
mon code postal est le 44300 ( eh oui il semble que nous ne soyons pas loin l'un de l'autre ;)
le INSEE de Nantes est 44109
j'ai bien cloné le module , pas d'erreurs
j'ai bien modifié le config.js ( avec mon INSEE)

mais j'ai pas le résultat escompté ( le % de pluie par tranche d'heure) et je n'ai pas de graph non plus
en fait ton module répond juste à la question " va t il pleuvoir dans l'heure"
et les 2 parametres showText et showGraph ne changent rien à l'affichage quelquesoit leur valeur

D'avance merci

**Comment by seramik** [comment]
bonjour
je teste ton module qui m'interresse beaucoup
mon code postal est le 44300 ( eh oui il semble que nous ne soyons pas loin l'un de l'autre ;)
j'ai bien cloné le module , pas d'erreurs
j'ai bien modifié le config.js ( avec mon code postal)
mais rien ne s'affiche sur mon mirroir
ça met : "pas de données disponibles" 
tu aurais une idée ?

D'avance merci

**Comment by seramik** [comment]
et quand j'essaye avec ton code postal ça marche mais ça ne m'affiche pas du tout ce que ça devrait
ça repond juste à la question " va t il pleuvoir dansd l'heure ?"

**Comment by tttooommm56** [comment]
Salut,
En fait s'il n'y a pas de pluie prévue dans l'heure, le graphe est masqué et le message "Pas de pluie prévue dans l'heure" s'affiche.
Si le module n'arrive pas à récupérer les infos de Météo France, il affiche "Pas de données disponible".
Demain on devrait avoir de la pluie dans notre coin, tu devrais voir le graphe s'afficher ;-)

**Comment by seramik** [comment]
ok je vais tester mais il n'y a pas de pluie de prévue ces jours ci ;)
je te tiendrais informé des mes résultats
merci pour la réponse.

**Comment by seramik** [comment]
farpait ! tout fonctionne bien :D
 
je regrette seulement que la prévision de pluie se limite juste à l'heure qui vienne

**Comment by tttooommm56** [comment]
Oui après ça dépend de Météo France ;-)
