### ISSUE TITLE
Plus de prévisions ?

### ISSUE THREAD

**Issue by smotx** [tttooommm56/MMM-RainForecast-FR#4]
Bonjour,

Merci pour ce module.

Question : il semble que cela donne les pluies prévisionnelles que pour l'heure à venir.

Est-il possible de voir sur plus de délais genre 24h ? 

Merci de votre réponse.

**Comment by tttooommm56** [comment]
Bonjour,

Oui le module utilise le service de prévision pluie de Météo France qui
n'est capable de prévoir que dans l'heure à venir :
http://www.meteofrance.com/previsions-meteo-france/previsions-pluie/
Ils augmenteront peut-être un jour ce délai...
