### ISSUE TITLE
Depuis plusieurs semaines : "pas de données disponibles"

### ISSUE THREAD

**Issue by Ponguipaple** [tttooommm56/MMM-RainForecast-FR#5]
Hello,
d'abord merci pour ce super boulot, ce module est une petite perle et hyper pratique!
Depuis plusieurs semaines cependant, le module m'affiche "Pas de données disponible". C'est arrivé d'un coup, je n'ai touché à rien.
Je suis en train de faire un 2e MagicMirror, j'installe le module sur une configuration toute neuve toute propre et dans une autre ville, et à nouveau "pas de données disponibles".
j'ai bien vérifié sur le site de MétéoFrance que ma ville est couverte par le service "pluie dans l'heure".

Une idée de ce qui se passe? Suis-je le seul dans ce cas?

A bientôt,
Damien

**Comment by tttooommm56** [comment]
Salut Damien,
Content de savoir que mon module est utile :-)
Rassure-toi j'ai également eu ce problème cet été.
En fait, Meteo France a mis à jour son site début aout et a changé ses web services.
J'ai donc dû adapter mon module.
Il faut donc que tu fasses un "git pull" dans le repertoire du module pour le mettre à jour.
Ensuite il faut aussi modifier la conf du module dans le fichier de conf du MagicMirror car ce n'est plus le code INSEE le parametre du webservice mais la latitude et la longitude.
La doc du module est à jour pour que tu vois comment le configurer.

Thomas

**Comment by Ponguipaple** [comment]
Impeccable, ça fonctionne nickel!! Merci à toi :-)
Damien
