### ISSUE TITLE
Graph

### ISSUE THREAD

**Issue by holenyoheader** [tttooommm56/MMM-RainForecast-FR#7]
Bonjour,

Pouvez-vous m'expliquer la représentation du graph ?
![Capture](https://user-images.githubusercontent.com/76501487/102945390-dea82000-44bd-11eb-9c81-233fd8196846.PNG)

Stéphane

**Comment by tttooommm56** [comment]
Le graphe représente les périodes de pluie prévues dans l'heure avec leur intensité sur 3 niveaux :

- niveau 1 : pluie faible
- niveau 2 : pluie modéré
- niveau 3 : pluie forte

Le libellé au-dessus du graphe indique le niveau de pluie actuel.

Sur votre graphe, on peut donc voir que la pluie est modérée de 1h30 à 1h50, puis pluie faible de 1h50 à 2h25.

**Comment by holenyoheader** [comment]
ok merci
Super job
Bien à vous,
